project_id = "sysbtcikrbrrgafffody"

[functions.send-contact-email]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.import-hospitals]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.find-missing-links]
verify_jwt = false

[functions.csrf-token]
verify_jwt = false

[functions.auth-cookie]
verify_jwt = false

[functions.logout]
verify_jwt = false

[functions.restore-session]
verify_jwt = false

[functions.import-texas-hospitals]
verify_jwt = false

[functions.remove-duplicates]
verify_jwt = false

[functions.fix-coordinates]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false

[functions.track]
verify_jwt = false

[functions.admin-get-user-profile]
verify_jwt = false

[functions.hospital-signup]
verify_jwt = false

[functions.hospital-duplicates]
verify_jwt = false

[functions.notify-application-status]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = false

[functions.import-csv-hospitals]
verify_jwt = false

[functions.fix-missing-states]
verify_jwt = false

[functions.send-mass-email]
verify_jwt = false

[functions.replace-opportunities]
verify_jwt = false

[functions.cleanup-unverified-users]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.batch-fetch-logos]
verify_jwt = false

[functions.fetch-logo]
verify_jwt = false

[functions.generate-amcas-description]
verify_jwt = false

[functions.clone-hospital-template]
verify_jwt = false

[functions.send-clinic-bulk-email]
verify_jwt = false

[functions.score-resume-match]
verify_jwt = false

[functions.bcs-email-autoresponder]
verify_jwt = false